version: "3.8"
# TODO Production version setup s
services:
  db:
    image: postgres:16
    container_name: fitness-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fitness_app_prod
      POSTGRES_USER: userProd
      POSTGRES_PASSWORD: GoodRequestProd
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fitness-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql://localhost:5432/fitness_app
    command: sh -c "npm install && npm run seed && npm start"
    volumes:
      - .:/app

volumes:
  pgdata:
