version: "3.8"

services:
  db:
    image: postgres:16
    container_name: fitness-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fitness_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: GoodRequest
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fitness-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgres://user:GoodRequest@db:5432/fitness_app
    command: sh -c "npm install && npm run seed && npm start"
    volumes:
      - .:/app

volumes:
  pgdata:
